inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: '2.4'
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Style/AsciiComments:
  Exclude:
    - 'config/initializers/money.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'config/application.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Style/GuardClause:
  Enabled: false
